pipeline {
  agent {
    docker {
      image 'softozor/shopozor-security-tests:v0.0.9'
    }
  }
  environment {
    JELASTIC_APP_CREDENTIALS = credentials('jelastic-app-credentials')
    JELASTIC_CREDENTIALS = credentials('jelastic-credentials')
  }
  stages {
    stage('Wake up Jelastic environment') {
        steps {
            script {
                SCRIPT_TO_RUN = './scripts/wake-up-env.sh'
                sh "chmod u+x $SCRIPT_TO_RUN"
                sh "$SCRIPT_TO_RUN $JELASTIC_APP_CREDENTIALS_USR $JELASTIC_APP_CREDENTIALS_PSW $JELASTIC_CREDENTIALS_USR $JELASTIC_CREDENTIALS_PSW $HIDORA_DOMAIN"
            }
        }
    }
    stage('Common Security Tests') {
        steps {
            withEnv(["HOME=$WORKSPACE"]) {
              catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                sh "cd tests/common && pytest --domain http://${HIDORA_DOMAIN}.hidora.com -ra --junitxml=common-test-report.xml"
              }
            }
        }
    }
    stage('Specific Security Tests') {
        steps {
            withEnv(["HOME=$WORKSPACE"]) {
                sh "cd tests/${APPLICATION_TYPE} && pytest --domain http://${HIDORA_DOMAIN}.hidora.com --graphql-endpoint graphql/ -ra --junitxml=specific-test-report.xml"
            }
        }
    }
  }
  post {
    always {
      script {
         junit "**/*.xml"
      }
    }
  }
}



